### ISSUE TITLE
Plugin fails to build since the latest update

### ISSUE THREAD

**Issue by YvesW** [VicSegers/gauntlet-minimap#1]
Probably because some of the resource ObjectID's changed. See e.g. https://github.com/rdutta/runelite-gauntlet/compare/bed17cdb2c8097e47a010b3b02dad4d84eec9b94...rdutta:9af84577f865330dd62f76081470d62d2765fa09

**Comment by VicSegers** [comment]
Fixed in runelite/plugin-hub#4340
